apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: do-not-preserve-host
# route:
#   preserve_host: false
  annotations: 
    konghq.com/preserve-host: "false"
upstream:
  host_header: bets.bets.svc
